### PR TITLE
Added populate functionality

### PR DESCRIPTION
**Pull request by marksyzm**
I needed to be able to populate fields via mongoose `ref` methodology, so I chucked it in. Look okay?

### CODE REVIEW

**Comment by marksyzm** [comment]
Ah, you want some tests... I'll sort it out ASAP

**Comment by larryprice** [comment]
Ah, you want some tests... I'll sort it out ASAP
Yes, please. Also, how do you feel about version `0.3.3` as opposed to `0.4`?

**Comment by marksyzm** [comment]
Well, I thought it was a new feature rather than a fix, hence the bump. But
I'm easy :)

**Comment by marksyzm** [comment]
@larryprice tests are in. I had to add `async` to do some populating and whatnot as I needed the IDs from the new documents and there's not really a way to grab those due to the callbacks being asynchronous in `mockgoose`. Look okay?

**Comment by larryprice** [comment]
Great... I should have time to verify this later today.

**Comment by larryprice** [comment]
looks good: it's in version 0.3.3 which i've just published. thanks for the PR and your cooperation on adding tests.

fyi i actually had someone else request this feature in a blog post i wrote a while back, so there was definitely an interest in this PR. thanks again.

**Comment by marksyzm** [comment]
No problem :) I needed it, and I could write it, so I did

**Pull request merged**
